### ISSUE TITLE
How do it change the value at which the menu is triggered?

### ISSUE THREAD

**Issue by anthonycha** [madebymade/jquery-navobile#14]
I want this to work on desktop view as well and not just on mobile. Can i change the break point to whatever I want? 

Thanks

**Comment by SebAshton** [comment]
Hi @anthonycha,

You can indeed change the breakpoint to be what ever you want.

Changing the breakpoint (in the css)[https://github.com/madebymade/jquery-navobile/blob/master/src/jquery.navobile.css#L9] will do the trick.

Thanks

S
